### ISSUE TITLE
FHIRValidationError

### ISSUE THREAD

**Issue by trentonyo** [FHIRType/workshop#110]
```
fhirclient.models.fhirabstractbase.FHIRValidationError: {root}:
  entry.0:
    resource:
      text:
        'Non-optional property "div" on <fhirclient.models.narrative.Narrative object at 0x00000196FFEC2C50> is missing'
```

Affected Endpoints: Centene

Reproducible Queries: Ask Trenton
